# -*- coding: utf-8 -*-
"""Kalkulator Turunan 1 Limit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/157Q0OE7Z2jWA-uL307cq2_9te-gyVPZN
"""

!pip install streamlit pyngrok --quiet

import streamlit as st
import sympy as sp

st.title("🧮 Kalkulator Turunan Pertama (Definisi Limit)")

# Input fungsi
fungsi_input = st.text_input("Masukkan fungsi f(x):", "x**2 + 3*x + 2")

# Input titik x
titik = st.number_input("Hitung turunan di titik x =", value=2.0, step=0.1)

# Tombol untuk menghitung
if st.button("Hitung Turunan"):
    try:
        # Inisialisasi simbol
        x, h = sp.symbols('x h')

        # Parse fungsi
        fungsi = sp.sympify(fungsi_input)

        # Rumus turunan berdasarkan limit
        turunan_limit = sp.limit((fungsi.subs(x, x + h) - fungsi) / h, h, 0)

        # Evaluasi turunan di titik x
        nilai_turunan = turunan_limit.subs(x, titik)

        # Tampilkan hasil
        st.latex(f"f(x) = {sp.latex(fungsi)}")
        st.latex(r"f'(x) = \lim_{h \to 0} \frac{f(x + h) - f(x)}{h}")
        st.latex(f"f'(x) = {sp.latex(turunan_limit)}")
        st.success(f"f'({titik}) = {nilai_turunan}")

    except Exception as e:
        st.error(f"Terjadi kesalahan: {e}")